deberia arreglar el error
no such table:
python manage.py makemigrations
python manage.py migrate --run-syncdb
